---
- name: Monitor Web App
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - http://ubuntu2.lab.test:5000/api/dadjoke
        delay: 5
  rules:
    - name: rebuild webserver if site down
      condition: event.url_check is defined
      action:
        debug:
          var: event

