---
- name: Monitor Web Critical Web App
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - http://ubuntu2.lab.test:5000/api/dadjoke
        delay: 20

  rules:
    - name: Rebuild Web App if status is not 200
      condition: event.url_check.status == down
      action:
        run_workflow_template:
          name: "Auto Remediate Web App"
          organization: "Default"
