---
- name: Monitor ZTP
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002
  rules:
    - name: Handle ZTP Arista event
      condition: event.payload.vendor is search("Arista", ignorecase=true)
      # To combat event storms, wait 1 minute if seeing same mac multiple times to perform action
      throttle:
        once_within: 60 seconds
        group_by_attributes:
          - event.payload.src_mac
      action:
        run_workflow_template:
          name: "Network ZTP"
          organization: "Default"
          job_args:
            extra_vars:
              src_mac: "{{ event.payload.src_mac }}"
              incident_short_desc: "ZTP started for '{{ event.payload.src_mac }}'"
              incident_descr: "ZTP started for '{{ event.payload.src_mac }}' from Vendor '{{ event.payload.vendor }}'"
              artifact:
                MSG: "Device MAC: '{{ event.payload.src_mac }}' from Vendor '{{ event.payload.vendor }}' is requesting to be provisioned, \
                  ZTP process has been initiated."
