---
- name: Monitor ZTP
  hosts: localhost
  sources:
    - elchico2007.eda.ztp:
        interface: "ens32"
        bpf_filter: "udp dst port 67"
  rules:
    - name: Handle ZTP Arista event
      condition: event.vendor is search("Arista", ignorecase=true)
      # To combat event storms, wait 1 minute if seeing same mac multiple times to perform action
      throttle:
        once_within: 60 seconds
        group_by_attributes:
          - event.src_mac
      action:
        run_workflow_template:
          name: "Network ZTP"
          organization: "Default"
          job_args:
            extra_vars:
              src_mac: "{{ event.src_mac }}"
              incident_short_desc: "ZTP started for '{{ event.src_mac }}'"
              incident_descr: "ZTP started for '{{ event.src_mac }}' from Vendor '{{ event.vendor }}'"
              artifact:
                MSG: "Device MAC: '{{ event.src_mac }}' from Vendor '{{ event.vendor }}' is requesting to be provisioned, \
                  ZTP process has been initiated."
