---
- name: Monitor ZTP
  hosts: localhost
  sources:
    - elchico2007.eda.ztp:
        interface: "eth0"
        filter: "udp dst port 67"
  rules:
    - name: Show me event
      condition: event.vendor_class_identifier is defined
      action:
        debug:
          var: event

