---
- name: Zabbix Agent Auto-Remediation
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Run Auto-Remediation playbook
      condition: event.payload is defined
      actions:
        - run_playbook:
            name: "playbooks/auto_remediate_zabbix_agent.yml"
        - print_event:
            pretty: true

